### ISSUE TITLE
Configurable timezone

### ISSUE THREAD

**Issue by phdelodder** [flyte/docker-motion-mqtt#1]
Can the docker image be updated to allow configurable timezone?

**Comment by flyte** [comment]
The way I've seen this done before is to add your own timezone as a volume, for example (off the top of my head):

```bash
docker run \
    ...
    -v /etc/localtime:/etc/localtime:ro \
    flyte/motion-mqtt
```

Does that work for you?

**Comment by flyte** [comment]
There's some discussion about this here for reference https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by phdelodder** [comment]
The first comment works as intented
