### ISSUE TITLE
Configurable data/event volume

### ISSUE THREAD

**Issue by phdelodder** [flyte/docker-motion-mqtt#2]
Can an additional volume be added, eg to store the motion detection files?

**Comment by flyte** [comment]
My use case is simply to publish the movement over MQTT so I'm not actually storing any captured footage. I may get round to implementing this at some point, but if you get it working for yourself then of course a PR is welcome :)

**Comment by flyte** [comment]
@phdelodder this can be accomplished by simply configuring a volume when you create the container:

```bash
docker run -d \
	--name motion-mqtt-office \
	-v /home/flyte/docker/motion-mqtt/office/config:/motion:ro \
	-v /mnt/storage/security/office:/capture \
	flyte/motion-mqtt
```

and then setting the desired config values in `motion.conf` to capture to `/capture`:

```
target_dir /capture
```

I'm going to close this for now - feel free to reopen if you need to.
